language: node_js
node_js:
  - "4"
  - "6"
  - "7"

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;use mysql; update user set password=PASSWORD('root') where user='root'; flush privileges;" -u root

script: yarn cover
# Send coverage data to Coveralls
after_script: cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose

